var require = {
  //  urlArgs: "bust=" + (new Date()).getTime(),
    baseUrl : "includes/lib-source",
    paths : {
        "jquery" : "jquery/jquery",
        "jquery-ui" : "smartadmin/js/libs/jquery-ui-1.10.3.min",
        "jquery.cookie":"jquery/jquery.cookie",
        "jquery.validate" : "smartadmin/js/plugin/jquery-validate/jquery.validate.min",
        "validate.expand" : "smartadmin/js/plugin/jquery-validate/validate.expand",
        "bootstrap" : "smartadmin/js/bootstrap/bootstrap",
        "bootstrap-paginator" : "smartadmin/js/bootstrap/bootstrap-paginator",
        "knockout":"smartadmin/js/libs/knockout",
        "fileinput":"smartadmin/js/bootsrap-fileinput/fileinput",
        "fileinput_locale_zh":"smartadmin/js/bootsrap-fileinput/fileinput_locale_zh",
        "app":"smartadmin/js/app",
        "basetools":"smartadmin/js/basetools",
        "datatables":"smartadmin/js/plugin/datatables-1.10.11/media/js/jquery.dataTables",
        /*    "dataTables.tableTools":"../smartadmin/js/plugin/datatables-1.10.11/extensions/dataTables.tableTools",*/
        "jeditable":"smartadmin/js/plugin/datatables-1.10.11/extensions/jeditable",
        "DT_bootstrap":"smartadmin/js/plugin/datatables-1.10.11/DT_bootstrap",
        "DT":"smartadmin/js/plugin/datatables-1.10.11/DT",
        "DF":"jquery/DF",
        "jquery.treeview":"smartadmin/js/plugin/jquery-treeview/jquery.treeview",
        "jquery.treeview.edit":"smartadmin/js/plugin/jquery-treeview/jquery.treeview.edit",
        "jquery.treeview.async":"smartadmin/js/plugin/jquery-treeview/jquery.treeview.async",
        "SmartNotification":"smartadmin/js/notification/SmartNotification",
        "jquery-confirm":"smartadmin/js/plugin/jquery-confirm/jquery-confirm",
        "json2form":"jquery/json2form",
        "jquery-form":"smartadmin/js/plugin/jquery-form/jquery-form.min",
        "bootstrap-select":"smartadmin/js/plugin/bootstrap-select/js/bootstrap-select",
        "bootstrap-datetimepicker":"smartadmin/js/plugin/datetimepicker/js/bootstrap-datetimepicker.min",
        "bootstrap-datetimepicker.zh-CN":"smartadmin/js/plugin/datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN",
        "summernote":"smartadmin/js/plugin/summernote/summernote",
        "summernote-zh-CN":"smartadmin/js/plugin/summernote/summernote-zh-CN",
        "dropzone":"smartadmin/js/plugin/dropzone/dropzone",
        "bootstrap-treeview":"smartadmin/js/plugin/bootstrap-treeview/bootstrap-treeview",
        "categorySel":"util/picker",
        "md5-min":"jquery/md5-min",
        "less":"smartadmin/js/less.min",

        "deptList":"appjs/sysmanage/dept/deptList",
        "deptAdd":"appjs/sysmanage/dept/deptAdd",
        "deptEdit":"appjs/sysmanage/dept/deptEdit",
        "roleList":"appjs/sysmanage/role/roleList",
        "roleAdd":"appjs/sysmanage/role/roleAdd",
        "roleEdit":"appjs/sysmanage/role/roleEdit",
        "userList":"appjs/sysmanage/user/userList",
        "userAdd":"appjs/sysmanage/user/userAdd",
        "userEdit":"appjs/sysmanage/user/userEdit",
        "dictionaryList":"appjs/sysmanage/dictionary/dictionaryList",
        "dictionaryAdd":"appjs/sysmanage/dictionary/dictionaryAdd",
        "dictionaryEdit":"appjs/sysmanage/dictionary/dictionaryEdit",
        "dicValAdd":"appjs/sysmanage/dictionary/dicValAdd",
        "resource":"appjs/sysmanage/resource/resource",

        "peopleEdit":"appjs/human/people/peopleEdit",
        "peopleAdd":"appjs/human/people/peopleAdd",
        "peopleList":"appjs/human/people/peopleList"
    },
    map: {
        '*': {
            'css': 'util/css'
        }
    },
    shim : {
        "jquery-ui" : ["jquery"],
        "bootstrap" : ["jquery"],//,"css!smartadmin/css/bootstrap.css"
        "SmartNotification" : ["jquery"],
        "md5-min":["jquery"],
        "jquery.treeview" : ["jquery"],
        "jquery.treeview.edit" : ["jquery.treeview"],
        "jquery.treeview.async" : ["jquery.treeview"],
        "datatables":["jquery"],//,"css!smartadmin/js/plugin/datatables-1.10.11/media/css/jquery.dataTables.css"
        "DT_bootstrap":["datatables"],
        "DT":["datatables","DT_bootstrap","bootstrap-datetimepicker","bootstrap-datetimepicker.zh-CN"],//"dataTables.tableTools","jeditable",
        "DF":["css!smartadmin/css/right.css"],
        "jquery.validate":["jquery"],
        "validate.expand":["jquery","jquery.validate"],
        "json2form":["jquery"],
        "jquery-form":["jquery"],
        "bootstrap-select":["jquery"],
        "basetools":["SmartNotification"],
        "bootstrap-datetimepicker":["jquery","css!smartadmin/js/plugin/datetimepicker/css/bootstrap-datetimepicker.css"],
        "bootstrap-datetimepicker.zh-CN":["bootstrap-datetimepicker"],
        "summernote-zh-CN":["summernote","css!smartadmin/css/summernote.css"],
        "fileinput":["css!smartadmin/js/bootsrap-fileinput/fileinput.css"],
        "fileinput_locale_zh":["fileinput"],
        "bootstrap-treeview":["jquery", 'css!smartadmin/js/plugin/bootstrap-treeview/bootstrap-treeview.css'],
        "knockout":["jquery"],
        "deptList" : ["jquery.treeview.edit","jquery.treeview.async","jquery-confirm","json2form"],
        "deptAdd":["jquery.validate","validate.expand"],
        "deptEdit":["jquery.validate","validate.expand"],

        "roleList" : ["jquery-confirm","json2form"],
        "roleAdd":["jquery.validate","validate.expand"],
        "roleEdit":["jquery.validate","validate.expand"],

        "userList" : ["jquery.treeview.edit","jquery.treeview.async","jquery-confirm","json2form"],
        "userAdd":["bootstrap-select","jquery.validate","validate.expand"],
        "userEdit":["bootstrap-select","jquery.validate","validate.expand"],

        "dictionaryList" : ["jquery-confirm","json2form"],
        "dictionaryAdd":["bootstrap-select","jquery.validate","validate.expand"],
        "dictionaryEdit":["bootstrap-select","jquery.validate","validate.expand"],
        "dicValAdd":["jeditable",'jquery.validate','validate.expand','jquery-form'],

        "peopleEdit": ["jquery.validate","validate.expand"],
        "peopleAdd": ["jquery.validate","validate.expand"],
        "peopleList": ["jquery-confirm","json2form"]
    }
};
